#!/bin/sh
### BEGIN INIT INFO
# Provides:          wifi-autostart
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Auto-start WiFi
### END INIT INFO

case "$1" in
  start)
    echo "Starting WiFi..."
    rfkill unblock wlan
    sleep 2
    ip link set wlan0 up
    wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
    sleep 5
    udhcpc -i wlan0
    ;;
  stop)
    killall wpa_supplicant
    ip link set wlan0 down
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
exit 0
